apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: yegobox/udagram-api-feed:v5
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            # Define the environment variable
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: postgres_host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: postgress_db
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_bucket
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_region
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: url
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_access_key
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: jwt_secret
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: aws_profile
