apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  selector:
    matchLabels:
      app: udagram-reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
        - name: udagram-reverseproxy
          image: yegobox/udagram-reverseproxy:v6
          ports:
            - containerPort: 8080
