apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    run: udagram-reverseproxy
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: udagram-reverseproxy
  selector:
    run: udagram-reverseproxy
