apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  selector:
    matchLabels:
      app: udagram-reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
        - name: udagram-reverseproxy
          image: yegobox/udagram-reverseproxy:v2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: udagram-reverseproxy-config
              mountPath: /etc/udagram-reverseproxy/udagram-reverseproxy.conf
              subPath: udagram-reverseproxy.conf
      volumes:
        - name: udagram-reverseproxy-config
          configMap:
            name: confudagram-reverseproxy
