apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-api-feed
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
